# Generated by Django 5.0.4 on 2024-05-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedVault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('date', models.DateField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
