# Generated by Django 5.0.4 on 2024-05-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedVault', '0003_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
