# Generated by Django 5.0.4 on 2024-05-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedVault', '0005_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
