# Generated by Django 5.0.4 on 2024-05-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedVault', '0006_alter_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
