# Generated by Django 5.0.4 on 2024-05-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedVault', '0007_alter_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='patient_no',
            field=models.BigIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
