# Generated by Django 5.0.4 on 2024-05-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedVault', '0009_remove_record_patient_no_alter_record_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
